language: c

branches:
  only:
    - master
    - osx

#r:
  # - devel
  # - release

os:
  - osx

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - rm -rf /usr/local/include/c++
  - rm -rf /usr/local/include/gfortran
  - brew install gcc
  - brew install open-mpi
  - mpiexec --version
  - mpicc -showme:incdirs
  - mpicc -showme:libdirs
  - mpicc -showme:compile
  - mpicc -showme:link
  - mpiexec -np 2 hostname
  - cd ../
  - R CMD build --no-resave-data --no-manual --no-build-vignettes pbdMPI

# r_packages:
#   - rlecuyer

install:
  - Rscript -e "install.packages('rlecuyer',repos='http://cran.r-project.org')"
  - R CMD check ./pbdMPI_*.tar.gz --as-cran --no-manual --no-vignettes
  - cat ./pbdMPI.Rcheck/pbdMPI-Ex.Rout
  - cat ./pbdMPI.Rcheck/pbdMPI-Ex.timings

script:
  - R CMD INSTALL ./pbdMPI_*.tar.gz

sudo: required

notifications:
  email:
    on_success: no
    on_failure: no
