language: r

branches:
  only:
    - master
    - osx

r:
  # - devel
  - release

os:
  - osx

### Remove c++ and gfortran links before install gcc because of conflicts
### between TRAVIS and brew
before_install:
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - rm -rf /usr/local/include/c++
  - rm -rf /usr/local/include/gfortran
  - brew install gcc
  - brew install open-mpi
  - mpiexec --version
  - mpicc -showme:incdirs
  - mpicc -showme:libdirs
  - mpicc -showme:compile
  - mpicc -showme:link
  - mpiexec -np 2 hostname

r_packages:
  - rlecuyer

sudo: required

notifications:
  email:
    on_success: never
    on_failure: never
