language: r

branches:
  only:
    - master
    - osx

r:
  # - devel
  - release

os:
  - osx

before_install:
  - curl -OL https://raw.githubusercontent.com/Homebrew/install/master/install
  - sudo brew install open-mpi
  - mpiexec -np 2 hostname

r_packages:
  - rlecuyer

sudo: required

notifications:
  email:
    on_success: never
    on_failure: never
